name: Playit_SSH_V3_2026
on:
  workflow_dispatch:
jobs:
  ssh_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-server
          sudo useradd -m -s /bin/bash shahan_user
          echo "shahan_user:pass1234" | sudo chpasswd
          sudo service ssh start

      - name: Install & Get Link
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update && sudo apt install playit -y
          
          echo "------------------------------------------------"
          echo "🚀 در حال تلاش برای دریافت لینک... به پایین دقت کنید"
          echo "------------------------------------------------"
          
          # اجرای مستقیم برای تولید لینک و قطع کردن بعد از 15 ثانیه
          timeout 15s playit || true
          
          echo "------------------------------------------------"
          echo "⬆️ اگر لینک بالا ظاهر شده، روی آن کلیک کنید"
          echo "اگر نشد، یکبار دیگر Workflow را اجرا کنید"
          echo "------------------------------------------------"

      - name: Keep Alive
        run: sleep 21600
